### ISSUE TITLE
Reorder values to minimize struct size

### ISSUE THREAD

**Issue by vusolapohvistr** [chastis/UniversityStuff#1]
https://github.com/chastis/UniversityStuff/blob/d318e43f002daac7ea573ea5aeedd35bc65235c3/FifthSemester/DataBase/Lab1/Lab1/main.cpp#L24-L27

Guide: https://timmurphy.org/2012/03/24/struct-sizes-in-c/

**Comment by chastis** [comment]
fixed, thank you
